env:
  global:
    - PATH=$PATH:$HOME/.cargo/bin
    - RUST_BACKTRACE=1
    - RUST_STABLE=1.25.0
os:
  - linux
  - osx
language: rust
rust:
  - 1.25.0
  - nightly-2018-02-05
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - if [ "${TRAVIS_RUST_VERSION}" = "$RUST_STABLE" ]; then
      bash cargo_install.sh rustfmt 0.9.0;
    elif [ "${TRAVIS_OS_NAME}" = linux ]; then
      bash cargo_install.sh clippy 0.0.186;
    fi
script:
  - if [ "${TRAVIS_RUST_VERSION}" = "$RUST_STABLE" ]; then
      (
        set -x;
        cargo fmt -- --write-mode=diff &&
        cargo test --release --verbose &&
        cargo test --release --verbose --manifest-path rust_sodium-sys/Cargo.toml
      );
    elif [ "${TRAVIS_OS_NAME}" = linux ]; then
      (
        set -x;
        cargo clippy &&
        cargo clippy --profile=test &&
        cargo clippy --manifest-path=rust_sodium-sys/Cargo.toml &&
        cargo clippy --profile=test --manifest-path=rust_sodium-sys/Cargo.toml
      );
    fi
before_cache:
  - cargo prune
