env:
  global:
    - PATH=$PATH:$HOME/.cargo/bin
    - RUST_BACKTRACE=1
os:
  - linux
  - osx
language: rust
rust:
  - stable
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - set -x;
    cargo fmt -- --check &&
    cargo test --release --verbose &&
    cargo test --release --verbose --manifest-path rust_sodium-sys/Cargo.toml &&
    cargo clippy &&
    cargo clippy --profile=test &&
    cargo clippy --manifest-path=rust_sodium-sys/Cargo.toml &&
    cargo clippy --profile=test --manifest-path=rust_sodium-sys/Cargo.toml
before_cache:
  - cargo prune
