[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Fast cryptographic library for Rust (bindings to libsodium)"
documentation = "https://docs.rs/rust_sodium"
homepage = "https://maidsafe.net"
license = "MIT OR Apache-2.0"
name = "rust_sodium"
readme = "README.md"
repository = "https://github.com/maidsafe/rust_sodium"
version = "0.2.0"

[dependencies]
libc = "~0.2.15"
rand = "~0.3.14"
rust_sodium-sys = { path = "rust_sodium-sys", version = "~0.2.0" }
rustc-serialize = { version = "~0.3.19", optional = true }
serde = { version = "~0.9.11", optional = true }
unwrap = "~1.1.0"

[dev-dependencies]
rmp-serde = "~0.12.4"
rustc-serialize = "~0.3.19"
serde = "~0.9.11"
serde_json = "~0.9.9"

[features]
benchmarks = []
default = ["serde", "get-libsodium"]
get-libsodium = ["rust_sodium-sys/get-libsodium"]
